#!/usr/bin/env python3
"""
ps_md_to_c.py -- PS/MD text -> a C header of flat data tables.

Reads the same PS/MD text asm2lm.py consumes (and pyld100's psmd.py
produces -- see pyld100/README.md) and emits a C header with one flat
array per input, plus a #define for its base address and element count.
No per-line structure, just the data and a size, sized for a DMA
transfer.

Usage:
    py ps_md_to_c.py -p prog.ps -o prog.h --name PROG
    py ps_md_to_c.py -p prog.ps -m prog.md1 --vtype 1 -o prog.h --name PROG
    py ps_md_to_c.py -m prog.md2 --vtype 2 -o data.h --name PROG

Output, given a name of PROG:
    #define PROG_PS_ADDR <base address>
    #define PROG_PS_SIZE <word count>          (4 words per PS location)
    static const uint16_t PROG_ps[PROG_PS_SIZE] = { ... };

    #define PROG_MD_ADDR <base address>
    #define PROG_MD_SIZE <element count>       (1 value per MD location)
    static const int16_t PROG_md[PROG_MD_SIZE] = { ... };   (--vtype 1)
    static const double PROG_md[PROG_MD_SIZE] = { ... };    (--vtype 2)

If the input's addresses aren't contiguous, the gap is zero-filled (a
flat C array can't represent a hole) and a warning is printed to stderr.
"""

from __future__ import annotations

import argparse
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import asm2lm  # noqa: E402  (reuse its PS/MD parsers -- same format, one source of truth)


def _fill(entries, default, label):
    """[(addr, value), ...] -> (base_addr, [value, ...] contiguous from base)."""
    if not entries:
        return 0, []
    entries = sorted(entries, key=lambda e: e[0])
    base = entries[0][0]
    top = entries[-1][0]
    by_addr = dict(entries)
    flat = []
    gaps = 0
    for addr in range(base, top + 1):
        v = by_addr.get(addr)
        if v is None:
            v = default
            gaps += 1
        flat.append(v)
    if gaps:
        print(f"ps_md_to_c.py: warning: {gaps} gap location(s) in {label}, zero-filled",
              file=sys.stderr)
    return base, flat


def _oct16(w):
    return f"0{w & 0xFFFF:06o}"


def _signed16(w):
    w &= 0xFFFF
    return str(w - 0x10000 if w >= 0x8000 else w)


def _emit_array(name, ctype, values, fmt, per_line=8):
    lines = [f"static const {ctype} {name}[{max(len(values), 1)}] = {{"]
    for i in range(0, len(values), per_line):
        chunk = values[i:i + per_line]
        lines.append("    " + ", ".join(fmt(v) for v in chunk) + ",")
    if not values:
        lines.append("    0,")
    lines.append("};")
    return "\n".join(lines)


def build_header(name, ps_entries=None, md_entries=None, md_vtype=1):
    guard = f"{name.upper()}_H"
    out = [
        "/* Generated by ps_md_to_c.py -- do not edit by hand. */",
        f"#ifndef {guard}",
        f"#define {guard}",
        "",
        "#include <stdint.h>",
        "",
    ]

    if ps_entries is not None:
        # Each PS entry is (addr, [w0, w1, w2, w3]) -- flatten to one word
        # per array slot, 4 words per location, matching the PS memory
        # layout directly.
        word_entries = []
        for addr, words in ps_entries:
            for i, w in enumerate(words):
                word_entries.append((addr * 4 + i, w))
        base_word, flat = _fill(word_entries, 0, "PS")
        base = base_word // 4
        out.append(f"#define {name}_PS_ADDR {base}")
        out.append(f"#define {name}_PS_SIZE {len(flat)}  /* words, 4 per PS location */")
        out.append("")
        out.append(_emit_array(f"{name}_ps", "uint16_t", flat, _oct16))
        out.append("")

    if md_entries is not None:
        base, flat = _fill(md_entries, 0, "MD")
        out.append(f"#define {name}_MD_ADDR {base}")
        out.append(f"#define {name}_MD_SIZE {len(flat)}  /* elements */")
        out.append("")
        if md_vtype == 1:
            out.append(_emit_array(f"{name}_md", "int16_t", flat, _signed16))
        else:
            out.append(_emit_array(f"{name}_md", "double", flat, repr))
        out.append("")

    out.append(f"#endif /* {guard} */")
    return "\n".join(out) + "\n"


def main(argv=None):
    ap = argparse.ArgumentParser(description="Convert PS/MD text into a C header of flat data tables.")
    ap.add_argument("-p", "--ps", metavar="FILE", help="PS source (asm2lm.py format)")
    ap.add_argument("-m", "--md", metavar="FILE", help="MD source (asm2lm.py format)")
    ap.add_argument("--vtype", type=int, choices=[1, 2], default=1,
                     help="MD encoding: 1=integer (default), 2=real")
    ap.add_argument("-o", "--output", required=True, metavar="FILE.h")
    ap.add_argument("--name", default="PROG", help="C identifier prefix (default PROG)")
    args = ap.parse_args(argv)

    if not args.ps and not args.md:
        ap.error("need at least one of -p (PS) or -m (MD)")

    ps_entries = asm2lm.parse_ps(args.ps) if args.ps else None
    md_entries = None
    if args.md:
        md_entries = (asm2lm.parse_md_vtype1(args.md) if args.vtype == 1
                      else asm2lm.parse_md_vtype2(args.md))

    text = build_header(args.name, ps_entries, md_entries, args.vtype)
    with open(args.output, "w") as fh:
        fh.write(text)
    print(f"wrote {args.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
